INSERT INTO DRONE (SERIAL_NO, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('11111', '111-DRN', 111, 50, 'IDLE');
INSERT INTO DRONE (SERIAL_NO, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('22222', '222-DRN', 222, 20, 'IDLE');
INSERT INTO DRONE (SERIAL_NO, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('33333', '333-DRN', 333, 70, 'IDLE');
INSERT INTO DRONE (SERIAL_NO, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('44444', '444-DRN', 444, 90, 'IDLE');
INSERT INTO DRONE (SERIAL_NO, MODEL, WEIGHT_LIMIT, BATTERY_CAPACITY, STATE) VALUES ('55555', '555-DRN', 555, 55, 'IDLE');

INSERT INTO MEDICATION (NAME, WEIGHT, CODE, IMAGE) VALUES ('MED111', '25', '11-MED', null);
INSERT INTO MEDICATION (NAME, WEIGHT, CODE, IMAGE) VALUES ('MED222', '25', '22-MED', null);
INSERT INTO MEDICATION (NAME, WEIGHT, CODE, IMAGE) VALUES ('MED333', '25', '33-MED', null);
