DROP TABLE IF EXISTS DRONE;
CREATE TABLE DRONE (
ID INT PRIMARY KEY AUTO_INCREMENT,
SERIAL_NO VARCHAR(100),
MODEL VARCHAR(15),
WEIGHT_LIMIT INT,
BATTERY_CAPACITY INT,
STATE VARCHAR(15),
MED_CODE VARCHAR(100)
);

DROP TABLE IF EXISTS MEDICATION; 
CREATE TABLE MEDICATION(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(100),
WEIGHT INT,
CODE VARCHAR(100),
IMAGE BLOB
);

DROP TABLE IF EXISTS DELIVERY; 
CREATE TABLE DELIVERY(
ID INT PRIMARY KEY AUTO_INCREMENT,
SERIAL_NO VARCHAR(100),
CODE VARCHAR(100)
);